package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"core_api/graph"
	"core_api/graph/model"
	"core_api/internal/repository"
	"time"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	db := r.DB

	userRepository := repository.NewUserRepository(db)
	user, err := userRepository.GetUserByID(id)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Email:     user.Email,
		Username:  user.Username,
		Age:       int32(user.Age),
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
	}, nil
}

// Squad is the resolver for the squad field.
func (r *queryResolver) Squad(ctx context.Context, id int32) (*model.Squad, error) {
	db := r.DB

	squadRepository := repository.NewSquadRepository(db)
	squad, err := squadRepository.GetSquadByID(id)
	if err != nil {
		return nil, err
	}

	squadPlayers, err := squadRepository.GetSquadPlayersBySquadID(int32(squad.ID))
	if err != nil {
		return nil, err
	}

	squadPlayersModel := make([]*model.SquadPlayer, len(squadPlayers))
	for i, squadPlayer := range squadPlayers {
		squadPlayersModel[i] = &model.SquadPlayer{
			ID:     int32(squadPlayer.ID),
			Player: &model.Player{ID: int32(squadPlayer.Player.ID), Name: squadPlayer.Player.Name},
		}
	}
	return &model.Squad{
		ID:      int32(squad.ID),
		Name:    squad.Name,
		Players: squadPlayersModel,
	}, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
