package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"core_api/graph"
	"core_api/graph/model"
	"core_api/internal/repository"
	service "core_api/internal/service/squad"
	"fmt"
	"pkg/models"
	"time"
)

// CreateSquad is the resolver for the createSquad field.
func (r *mutationResolver) CreateSquad(ctx context.Context, input model.CreateSquadInput) (*model.Squad, error) {
	db := r.DB

	userID, _ := ctx.Value("userID").(string)
	if userID == "" {
		return nil, fmt.Errorf("User Unauthorized")
	}
	squadService := service.NewSquadService(repository.NewUserRepository(db), repository.NewSquadRepository(db))
	squad, err := squadService.CreateSquad(ctx, &input)
	if err != nil {
		return nil, err
	}
	return squad, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	db := r.DB
	user := models.User{
		Email:            input.Email,
		Username:         input.Username,
		Age:              uint(input.Age),
		FavoriteTeamID:   uint(input.FavoriteTeamID),
		FavoritePlayerID: uint(input.FavoritePlayerID),
		CountryID:        uint(input.CountryID),
		Gender:           input.Gender,
	}
	userRepository := repository.NewUserRepository(db)
	err := userRepository.CreateUser(&user)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Email:     user.Email,
		Username:  user.Username,
		Age:       int32(user.Age),
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
	}, nil
}

// SubstitutePlayer is the resolver for the substitutePlayer field.
func (r *mutationResolver) SubstitutePlayer(ctx context.Context, input model.SubstitutePlayerInput) (*model.Squad, error) {
	db := r.DB

	userID, _ := ctx.Value("userID").(string)
	if userID == "" {
		return nil, fmt.Errorf("User Unauthorized")
	}

	squadService := service.NewSquadService(repository.NewUserRepository(db), repository.NewSquadRepository(db))
	squad, err := squadService.SubstitutePlayer(ctx, &input)
	if err != nil {
		return nil, err
	}
	return squad, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
