package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"core_api/graph/model"
	"core_api/internal/repository"
	service "core_api/internal/service/stats"
)

// GetMatches is the resolver for the getMatches field.
func (r *queryResolver) GetMatches(ctx context.Context) ([]*model.GameMatch, error) {
	db := r.DB

	statsRepository := repository.NewStatsRepository(db)
	statsService := service.NewStatsService(statsRepository)
	return statsService.GetMaches()
}

// GetTables is the resolver for the getTables field.
func (r *queryResolver) GetTables(ctx context.Context) ([]*model.Table, error) {
	db := r.DB

	statsRepository := repository.NewStatsRepository(db)
	statsService := service.NewStatsService(statsRepository)
	return statsService.GetTable()
}
