// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Country struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type CreateSquadInput struct {
	Name    string                    `json:"name"`
	Players []*CreateSquadPlayerInput `json:"players"`
}

type CreateSquadPlayerInput struct {
	PlayerID      int32   `json:"playerId"`
	Captain       bool    `json:"captain"`
	ViceCaptain   bool    `json:"viceCaptain"`
	Injured       bool    `json:"injured"`
	Suspended     bool    `json:"suspended"`
	Score         int32   `json:"score"`
	Price         float64 `json:"price"`
	IsStarting    bool    `json:"isStarting"`
	PositionOrder int32   `json:"positionOrder"`
}

type CreateUserInput struct {
	Email            string `json:"email"`
	Username         string `json:"username"`
	Age              int32  `json:"age"`
	FavoriteTeamID   int32  `json:"favoriteTeamId"`
	FavoritePlayerID int32  `json:"favoritePlayerId"`
	CountryID        int32  `json:"countryId"`
	Gender           string `json:"gender"`
}

type GameMatch struct {
	Round   int32    `json:"round"`
	Matches []*Match `json:"Matches"`
}

type GameWeek struct {
	Round int32 `json:"round"`
}

type Match struct {
	Date          string    `json:"date"`
	Time          string    `json:"time"`
	Gameweek      *GameWeek `json:"gameweek"`
	HomeTeam      *Team     `json:"homeTeam"`
	AwayTeam      *Team     `json:"awayTeam"`
	Completed     bool      `json:"completed"`
	HomeTeamScore int32     `json:"HomeTeamScore"`
	AwayTeamScore int32     `json:"AwayTeamScore"`
}

type Mutation struct {
}

type Player struct {
	ID       int32    `json:"id"`
	Name     string   `json:"name"`
	Position string   `json:"position"`
	Country  *Country `json:"country"`
}

type Query struct {
}

type Squad struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Players []*SquadPlayer `json:"players"`
}

type SquadPlayer struct {
	ID            int32   `json:"id"`
	Player        *Player `json:"player"`
	Captain       bool    `json:"captain"`
	ViceCaptain   bool    `json:"viceCaptain"`
	Injured       bool    `json:"injured"`
	Suspended     bool    `json:"suspended"`
	Score         int32   `json:"score"`
	Price         float64 `json:"price"`
	IsStarting    bool    `json:"isStarting"`
	PositionOrder int32   `json:"positionOrder"`
}

type SubstitutePlayerInput struct {
	SquadPlayerIDToSubstitute int32 `json:"squadPlayerIdToSubstitute"`
	SquadPlayerIDToReplace    int32 `json:"squadPlayerIdToReplace"`
}

type Team struct {
	ID      int32    `json:"id"`
	Name    string   `json:"name"`
	Country *Country `json:"country"`
}

type User struct {
	ID             string   `json:"id"`
	Email          string   `json:"email"`
	Username       string   `json:"username"`
	Age            int32    `json:"age"`
	FavoriteTeam   *Team    `json:"favoriteTeam"`
	FavoritePlayer *Player  `json:"favoritePlayer"`
	Squad          *Squad   `json:"squad,omitempty"`
	Country        *Country `json:"country"`
	Gender         string   `json:"gender"`
	CreatedAt      string   `json:"createdAt"`
}

type UserRegistration struct {
	Username        string `json:"username"`
	Email           string `json:"email"`
	Age             int32  `json:"age"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	Phone           string `json:"phone"`
	Gender          string `json:"gender"`
}
