type Squad {
  id: Int!
  name: String!
  players: [SquadPlayer!]!
}

type SquadPlayer {
  id: Int!
  player: Player!
  captain: Boolean!
  viceCaptain: Boolean!
  injured: Boolean!
  suspended: Boolean!
  score: Int!
  price: Float!
  isStarting: Boolean!
  positionOrder: Int!
}

input CreateSquadInput {
  name: String!
  players: [CreateSquadPlayerInput!]!
}


input CreateSquadPlayerInput {
  playerId: Int!
  captain: Boolean!
  viceCaptain: Boolean!
  injured: Boolean!
  suspended: Boolean!
  score: Int!
  price: Float!
  isStarting: Boolean!
  positionOrder: Int!
}

type Mutation {
  createSquad(input: CreateSquadInput!): Squad!
  createUser(input: CreateUserInput!): User!
}