scalar DateTime
scalar Date

type GameWeek {
    round: Int!
}

type Match {
    date: Date!
    time: DateTime!
    gameweek: GameWeek!
    homeTeam: Team!
    awayTeam: Team!
    completed: Boolean!
    HomeTeamScore: Int!
    AwayTeamScore: Int!
}

type Table {
    team: Team
    position: Int!
    played: Int!
    wins: Int!
    losses: Int!
    scoresFor: Int!
    scoresAgainst: Int!
    draws: Int!
    points: Int!
    scoreDiffFormatted: Int!
}

type GameMatch {
    round: Int!
    Matches: [Match!]!
}

extend type Query {
    getMatches: [GameMatch!]!
    getTables: [Table!]!
}