name: Fantasy CI

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - dev
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Setup-Gloang
              uses: actions/setup-go@v4
              with:
                go-version: '1.25.3'
                check-latest: true
            
            - run: go version

            - name: Install-Golang Dependencies
              run: go mod download
            
            - name: Build Fantasy Engine
              run: make build
              
            - name: Runt Linting
              run: make lint

            - name: Run Tests
              run: make test
            