package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"core_api/graph/model"
	"core_api/internal/auth"
	"core_api/internal/repository"
	"fmt"
	"pkg/database"
	"pkg/models"
	"time"

	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, code string) (*model.AuthPayload, error) {
	googleUserInfo, err := auth.GetGoogleUserInfo(code)
	if err != nil {
		return nil, err
	}

	userRepository := repository.NewUserRepository(database.DB)
	user, _ := userRepository.GetUserByEmail(googleUserInfo.Email)
	if user == nil {
		user = &models.User{
			Email:            googleUserInfo.Email,
			Username:         googleUserInfo.Name,
			Age:              0,
			FavoriteTeamID:   0,
			FavoritePlayerID: 0,
			CountryID:        0,
			Gender:           "M",
			PasswordHash:     "",
		}
		userRepository.CreateUser(user)
	}
	token, err := auth.GenerateJWT(user.ID)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:       user.ID,
			Email:    user.Email,
			Username: user.Username,
		},
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, ok := ctx.Value("userID").(string)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}
	if userID != id {
		return nil, fmt.Errorf("unauthorized")
	}
	db := database.DB

	userRepository := repository.NewUserRepository(db)
	user, err := userRepository.GetUserByID(id)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Email:     user.Email,
		Username:  user.Username,
		Age:       int32(user.Age),
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, _ := ctx.Value("userID").(string)
	if userID == "" {
		return nil, fmt.Errorf("Unauthorized")
	}
	db := database.DB
	userRepository := repository.NewUserRepository(db)
	user, err := userRepository.GetUserByID(userID)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Email:     user.Email,
		Username:  user.Username,
		Age:       int32(user.Age),
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
	}, nil
}

// Squad is the resolver for the squad field.
func (r *queryResolver) Squad(ctx context.Context, id int32) (*model.Squad, error) {
	_, ok := ctx.Value("userID").(string)
	if !ok {
		return nil, fmt.Errorf("Unauthorized")
	}
	db := database.DB

	squadRepository := repository.NewSquadRepository(db)
	squad, err := squadRepository.GetSquadByID(id)
	if err != nil {
		return nil, err
	}

	squadPlayers, err := squadRepository.GetSquadPlayersBySquadID(int32(squad.ID))
	if err != nil {
		return nil, err
	}

	squadPlayersModel := make([]*model.SquadPlayer, len(squadPlayers))
	for i, squadPlayer := range squadPlayers {
		squadPlayersModel[i] = &model.SquadPlayer{
			ID:     int32(squadPlayer.ID),
			Player: &model.Player{ID: int32(squadPlayer.Player.ID), Name: squadPlayer.Player.Name},
		}
	}
	return &model.Squad{
		ID:      int32(squad.ID),
		Name:    squad.Name,
		Players: squadPlayersModel,
	}, nil
}

// GoogleAuthURL is the resolver for the googleAuthUrl field.
func (r *queryResolver) GoogleAuthURL(ctx context.Context) (string, error) {
	state := uuid.New().String()
	return auth.GetGoogleAuthURL(state), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
