package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"core_api/graph/model"
	"core_api/internal/repository"
	"pkg/database"
	"pkg/models"
	"time"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	db := database.DB
	user := models.User{
		Email:            input.Email,
		Username:         input.Username,
		Age:              uint(input.Age),
		FavoriteTeamID:   uint(input.FavoriteTeamID),
		FavoritePlayerID: uint(input.FavoritePlayerID),
		CountryID:        uint(input.CountryID),
		Gender:           input.Gender,
	}
	userRepository := repository.NewUserRepository(db)
	err := userRepository.CreateUser(&user)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Email:     user.Email,
		Username:  user.Username,
		Age:       int32(user.Age),
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	db := database.DB

	userRepository := repository.NewUserRepository(db)
	user, err := userRepository.GetUserByID(id)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Email:     user.Email,
		Username:  user.Username,
		Age:       int32(user.Age),
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
