package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"core_api/graph/model"
	"core_api/internal/repository"
	service "core_api/internal/service/user"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.UserRegistration) (*model.User, error) {
	db := r.DB

	userService := service.NewUserService(repository.NewUserRepository(db))
	registerUserValidator := &service.CreateUserValidation{
		Username:        input.Username,
		Email:           input.Email,
		Gender:          input.Gender,
		Password:        input.Password,
		ConfirmPassword: input.ConfirmPassword,
		Age:             int(input.Age),
		Phone:           input.Phone,
	}
	if err := service.ValidatUserRegistartion(*registerUserValidator); err != nil {
		return nil, err
	}
	createdUser, err := userService.RegisterUser(&input)
	if err != nil {
		return nil, err
	}
	return createdUser, nil
}
